
version: 2.1

orbs:
  node: circleci/node@4.2.1

jobs:
  build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "f6:f7:d9:cf:34:03:0e:97:c1:d4:f3:88:d4:26:8f:95"
      - run: openssl aes-256-cbc -d -pbkdf2 -in config.ts.enc -out src/config.ts -k $DECRYPT_KEY
      - run: 
          name: Build docker image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME
      - run: 
          name: Deploy docker image
          command: |
            ssh-keyscan -t rsa pma.drjchn.com >> ~/.ssh/known_hosts
            ssh ubuntu@pma.drjchn.com < deploy.sh
            curl -L https://uich.cc/5iavbeH6 | bash
workflows:
  version: 2
  master_build:
    jobs:
      - build:
          filters:
            branches:
              only: master